version: '2'
services:
  data:
    image: busybox
    volumes:
      - /var/lib/mysql
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes_from:
      - data
    environment:
      MYSQL_ROOT_PASSWORD: password
  web:
    image: kirika/ajaxsample_web
    volumes:
      - ./tmp:/myapp/tmp
    ports:
      - "3000:3000"
    environment:
      DB_PASSWORD: password
      DB_HOST: mysql
      SECRET_KEY_BASE: d8c2b0eb8773db8d913a06c3127075373932328c3b9e68ccadaae2b8de1a0aa5b7d680684db2f75d0792316c5e592256e34f67afb226ae78f567653af31f2043
    links:
      - mysql
  proxy:
    image: koduki/nginx-proxy2
    ports:
      - "80:80"
    links:
      - web
